//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyers.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public System.DateTime Date { get; set; }
        public string Issue { get; set; }
        public string Status { get; set; }
        public int Lid { get; set; }
        public int Cid { get; set; }
    
        public virtual client client { get; set; }
        public virtual lawyer lawyer { get; set; }
    }
}
