//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyers.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Profile_ID { get; set; }
        public string Pic_path { get; set; }
        public string Experince { get; set; }
        public string Specialiized_In { get; set; }
        public string Total_Cases { get; set; }
        public string Description { get; set; }
    }
}
